<a href="https://colab.research.google.com/github/dibyanshu999/Exploratory-Data-analysis-in-python/blob/main/Data_Gathering_for_ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

USING CSV file

In [ ]:
import pandas as pd

In [ ]:
#local csv file
df=pd.read_csv('/content/housing.csv')
print(df)

       Unnamed: 0  MedInc  HouseAge  AveRooms  AveBedrms  Population  \
0               0  8.3252      41.0  6.984127   1.023810       322.0
1               1  8.3014      21.0  6.238137   0.971880      2401.0
2               2  7.2574      52.0  8.288136   1.073446       496.0
3               3  5.6431      52.0  5.817352   1.073059       558.0
4               4  3.8462      52.0  6.281853   1.081081       565.0
...           ...     ...       ...       ...        ...         ...
20635       20635  1.5603      25.0  5.045455   1.133333       845.0
20636       20636  2.5568      18.0  6.114035   1.315789       356.0
20637       20637  1.7000      17.0  5.205543   1.120092      1007.0
20638       20638  1.8672      18.0  5.329513   1.171920       741.0
20639       20639  2.3886      16.0  5.254717   1.162264      1387.0

       AveOccup  Latitude  Longitude
0      2.555556     37.88    -122.23
1      2.109842     37.86    -122.22
2      2.802260     37.85    -122.24
3      2.547945     37.85    -122.25
4      2.181467     37.85    -122.25
...         ...       ...        ...
20635  2.560606     39.48    -121.09
20636  3.122807     39.49    -121.21
20637  2.325635     39.43    -121.22
20638  2.123209     39.43    -121.32
20639  2.616981     39.37    -121.24

[20640 rows x 9 columns]

In [ ]:
#opening a csv file using an url
import requests
from io import StringIO
ur1 = "https://raw.githubusercontent.com/cs109/2014_data/master/countries.csv"
headers = {"User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:66.0) Gecko/20100101 Firefox/66.0"}
req = requests.get(ur1, headers=headers)
data = StringIO(req.text)

pd.read_csv(data)

       Country         Region
0      Algeria         AFRICA
1       Angola         AFRICA
2        Benin         AFRICA
3     Botswana         AFRICA
4      Burkina         AFRICA
..         ...            ...
189   Paraguay  SOUTH AMERICA
190       Peru  SOUTH AMERICA
191   Suriname  SOUTH AMERICA
192    Uruguay  SOUTH AMERICA
193  Venezuela  SOUTH AMERICA

[194 rows x 2 columns]

In [ ]:
#sep parameter
#for tsv tab separated files, sep = '\t'

In [ ]:
#header parameter = uses the first row as the column label names
pd.read_csv('housing.csv',header=1)

,0,8.3252,41.0,6.984126984126984,1.0238095238095237,322.0,2.5555555555555554,37.88,-122.23
0,1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22
1,2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24
2,3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25
3,4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25
4,5,4.0368,52.0,4.761658,1.103627,413.0,2.139896,37.85,-122.25
...,...,...,...,...,...,...,...,...,...
20634,20635,1.5603,25.0,5.045455,1.133333,845.0,2.560606,39.48,-121.09
20635,20636,2.5568,18.0,6.114035,1.315789,356.0,3.122807,39.49,-121.21
20636,20637,1.7000,17.0,5.205543,1.120092,1007.0,2.325635,39.43,-121.22
20637,20638,1.8672,18.0,5.329513,1.171920,741.0,2.123209,39.43,-121.32
20638,20639,2.3886,16.0,5.254717,1.162264,1387.0,2.616981,39.37,-121.24

In [ ]:
#use_cols parameter : only prints columns required
pd.read_csv('housing.csv', usecols=['MedInc','HouseAge','AveRooms'] )

       MedInc  HouseAge  AveRooms
0      8.3252      41.0  6.984127
1      8.3014      21.0  6.238137
2      7.2574      52.0  8.288136
3      5.6431      52.0  5.817352
4      3.8462      52.0  6.281853
...       ...       ...       ...
20635  1.5603      25.0  5.045455
20636  2.5568      18.0  6.114035
20637  1.7000      17.0  5.205543
20638  1.8672      18.0  5.329513
20639  2.3886      16.0  5.254717

[20640 rows x 3 columns]

In [ ]:
#skiprows/nrows parameter
pd.read_csv('housing.csv',skiprows=[0,5])
pd.read_csv('housing.csv',nrows=5)

,Unnamed: 0,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude
0,0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23
1,1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22
2,2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24
3,3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25
4,4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25

In [ ]:
#encoding parameter : for datasets other than utf-8 encoding
pd.read_csv('/content/wiki_latin_data_v1.csv', encoding='latin-1')

,Latin Word,Cleaned Latin Word,POS,Lemma,Aspect,Tense,VerbForm,Voice,Mood,Number,Person,Case,Gender,Source URL
0,6tus,tus,NOUN,tus,NaN,NaN,NaN,NaN,NaN,Sing,NaN,Nom,Masc,https://en.wiktionary.org/wiki/Category:Latin_...
1,7mus,mus,VERB,mus,NaN,Pres,NaN,Act,Sub,Sing,3.0,NaN,NaN,https://en.wiktionary.org/wiki/Category:Latin_...
2,8vus,vus,NOUN,uus,NaN,NaN,NaN,NaN,NaN,Sing,NaN,Nom,Masc,https://en.wiktionary.org/wiki/Category:Latin_...
3,Unsupported titles/:,Unsupportedtitles,ADJ,Unsupportedtitles,NaN,NaN,NaN,NaN,NaN,Sing,NaN,Nom,Masc,https://en.wiktionary.org/wiki/Category:Latin_...
4,-a,a,ADP,ab,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://en.wiktionary.org/wiki/Category:Latin_...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41809,zygomaticus,zygomaticus,NOUN,zygomaticus,NaN,NaN,NaN,NaN,NaN,Sing,NaN,Nom,Masc,https://en.wiktionary.org/wiki/Category:Latin_...
41810,zygostates,zygostates,NOUN,zygostatis,NaN,NaN,NaN,NaN,NaN,Plur,NaN,Nom,Fem,https://en.wiktionary.org/wiki/Category:Latin_...
41811,Zygris,Zygris,PROPN,Zygris,NaN,NaN,NaN,NaN,NaN,Sing,NaN,Gen,Masc,https://en.wiktionary.org/wiki/Category:Latin_...
41812,Zyras,Zyras,NOUN,Zyras,NaN,NaN,NaN,NaN,NaN,Plur,NaN,Acc,Fem,https://en.wiktionary.org/wiki/Category:Latin_...
41813,zythum,zythum,NOUN,zythus,NaN,NaN,NaN,NaN,NaN,Sing,NaN,Acc,Masc,https://en.wiktionary.org/wiki/Category:Latin_...

In [ ]:
#skip bad lines: for parser error
#pd.read_csv('dataset.csv', error_bad_lines=False)

In [ ]:
#dtypes parameter
pd.read_csv('aug_test.csv').info()
pd.read_csv('aug_test.csv',dtype={'target':int}).info() #saves storage by coverting unnecessary float dtype unto int

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2129 entries, 0 to 2128
Data columns (total 13 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   enrollee_id             2129 non-null   int64
 1   city                    2129 non-null   object
 2   city_development_index  2129 non-null   float64
 3   gender                  1621 non-null   object
 4   relevent_experience     2129 non-null   object
 5   enrolled_university     2098 non-null   object
 6   education_level         2077 non-null   object
 7   major_discipline        1817 non-null   object
 8   experience              2124 non-null   object
 9   company_size            1507 non-null   object
 10  company_type            1495 non-null   object
 11  last_new_job            2089 non-null   object
 12  training_hours          2129 non-null   int64
dtypes: float64(1), int64(2), object(10)
memory usage: 216.4+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2129 entries, 0 to 2128
Data columns (total 13 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   enrollee_id             2129 non-null   int64
 1   city                    2129 non-null   object
 2   city_development_index  2129 non-null   float64
 3   gender                  1621 non-null   object
 4   relevent_experience     2129 non-null   object
 5   enrolled_university     2098 non-null   object
 6   education_level         2077 non-null   object
 7   major_discipline        1817 non-null   object
 8   experience              2124 non-null   object
 9   company_size            1507 non-null   object
 10  company_type            1495 non-null   object
 11  last_new_job            2089 non-null   object
 12  training_hours          2129 non-null   int64
dtypes: float64(1), int64(2), object(10)
memory usage: 216.4+ KB

In [ ]:
#handling dates: converting date time object in csv to datetime dtype
pd.read_csv('IPL Matches 2008-2020.csv').info()
pd.read_csv('IPL Matches 2008-2020.csv', parse_dates=['date']).info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 816 entries, 0 to 815
Data columns (total 17 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               816 non-null    int64
 1   city             803 non-null    object
 2   date             816 non-null    object
 3   player_of_match  812 non-null    object
 4   venue            816 non-null    object
 5   neutral_venue    816 non-null    int64
 6   team1            816 non-null    object
 7   team2            816 non-null    object
 8   toss_winner      816 non-null    object
 9   toss_decision    816 non-null    object
 10  winner           812 non-null    object
 11  result           812 non-null    object
 12  result_margin    799 non-null    float64
 13  eliminator       812 non-null    object
 14  method           19 non-null     object
 15  umpire1          816 non-null    object
 16  umpire2          816 non-null    object
dtypes: float64(1), int64(2), object(14)
memory usage: 108.5+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 816 entries, 0 to 815
Data columns (total 17 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               816 non-null    int64
 1   city             803 non-null    object
 2   date             816 non-null    datetime64[ns]
 3   player_of_match  812 non-null    object
 4   venue            816 non-null    object
 5   neutral_venue    816 non-null    int64
 6   team1            816 non-null    object
 7   team2            816 non-null    object
 8   toss_winner      816 non-null    object
 9   toss_decision    816 non-null    object
 10  winner           812 non-null    object
 11  result           812 non-null    object
 12  result_margin    799 non-null    float64
 13  eliminator       812 non-null    object
 14  method           19 non-null     object
 15  umpire1          816 non-null    object
 16  umpire2          816 non-null    object
dtypes: datetime64[ns](1), float64(1), int64(2), object(13)
memory usage: 108.5+ KB

In [ ]:
#convertors
def rename(name):
  if name == "Royal Challengers Bangalore":
    return "49"
  else :
    return name

In [ ]:
rename("Royal Challengers Bangalore")

'49'

In [ ]:
pd.read_csv('IPL Matches 2008-2020.csv',converters={'team1': rename})

,id,city,date,player_of_match,venue,neutral_venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,eliminator,method,umpire1,umpire2
0,335982,Bangalore,2008-04-18,BB McCullum,M Chinnaswamy Stadium,0,49,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,N,NaN,Asad Rauf,RE Koertzen
1,335983,Chandigarh,2008-04-19,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",0,Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,N,NaN,MR Benson,SL Shastri
2,335984,Delhi,2008-04-19,MF Maharoof,Feroz Shah Kotla,0,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,Delhi Daredevils,wickets,9.0,N,NaN,Aleem Dar,GA Pratapkumar
3,335985,Mumbai,2008-04-20,MV Boucher,Wankhede Stadium,0,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,Royal Challengers Bangalore,wickets,5.0,N,NaN,SJ Davis,DJ Harper
4,335986,Kolkata,2008-04-20,DJ Hussey,Eden Gardens,0,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,Kolkata Knight Riders,wickets,5.0,N,NaN,BF Bowden,K Hariharan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
811,1216547,Dubai,2020-09-28,AB de Villiers,Dubai International Cricket Stadium,0,49,Mumbai Indians,Mumbai Indians,field,Royal Challengers Bangalore,tie,NaN,Y,NaN,Nitin Menon,PR Reiffel
812,1237177,Dubai,2020-11-05,JJ Bumrah,Dubai International Cricket Stadium,0,Mumbai Indians,Delhi Capitals,Delhi Capitals,field,Mumbai Indians,runs,57.0,N,NaN,CB Gaffaney,Nitin Menon
813,1237178,Abu Dhabi,2020-11-06,KS Williamson,Sheikh Zayed Stadium,0,49,Sunrisers Hyderabad,Sunrisers Hyderabad,field,Sunrisers Hyderabad,wickets,6.0,N,NaN,PR Reiffel,S Ravi
814,1237180,Abu Dhabi,2020-11-08,MP Stoinis,Sheikh Zayed Stadium,0,Delhi Capitals,Sunrisers Hyderabad,Delhi Capitals,bat,Delhi Capitals,runs,17.0,N,NaN,PR Reiffel,S Ravi
815,1237181,Dubai,2020-11-10,TA Boult,Dubai International Cricket Stadium,0,Delhi Capitals,Mumbai Indians,Delhi Capitals,bat,Mumbai Indians,wickets,5.0,N,NaN,CB Gaffaney,Nitin Menon

In [ ]:
#na_values parameter : converts value to NaN
pd.read_csv('aug_test.csv',na_values=['Male'])

,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours
0,32403,city_41,0.827,NaN,Has relevent experience,Full time course,Graduate,STEM,9,<10,NaN,1,21
1,9858,city_103,0.920,Female,Has relevent experience,no_enrollment,Graduate,STEM,5,NaN,Pvt Ltd,1,98
2,31806,city_21,0.624,NaN,No relevent experience,no_enrollment,High School,NaN,<1,NaN,Pvt Ltd,never,15
3,27385,city_13,0.827,NaN,Has relevent experience,no_enrollment,Masters,STEM,11,10/49,Pvt Ltd,1,39
4,27724,city_103,0.920,NaN,Has relevent experience,no_enrollment,Graduate,STEM,>20,10000+,Pvt Ltd,>4,72
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2124,1289,city_103,0.920,NaN,No relevent experience,no_enrollment,Graduate,Humanities,16,NaN,Public Sector,4,15
2125,195,city_136,0.897,NaN,Has relevent experience,no_enrollment,Masters,STEM,18,NaN,NaN,2,30
2126,31762,city_100,0.887,NaN,No relevent experience,no_enrollment,Primary School,NaN,3,NaN,Pvt Ltd,never,18
2127,7873,city_102,0.804,NaN,Has relevent experience,Full time course,High School,NaN,7,100-500,Public Sector,1,84
2128,12215,city_102,0.804,NaN,Has relevent experience,no_enrollment,Masters,STEM,15,10000+,Pvt Ltd,2,11

In [ ]:
#loading a huge dataset in chunks: for handling very large datasets
dfs=pd.read_csv('aug_test.csv',chunksize=500)

In [ ]:
for chunks in dfs:
    print(chunks.shape)

(500, 13)
(500, 13)
(500, 13)
(500, 13)
(129, 13)

JSON **FILES**

In [ ]:
pd.read_json('train.json')

          id      cuisine                                        ingredients
0      10259        greek  [romaine lettuce, black olives, grape tomatoes...
1      25693  southern_us  [plain flour, ground pepper, salt, tomatoes, g...
2      20130     filipino  [eggs, pepper, salt, mayonaise, cooking oil, g...
3      22213       indian                [water, vegetable oil, wheat, salt]
4      13162       indian  [black pepper, shallots, cornflour, cayenne pe...
...      ...          ...                                                ...
39769  29109        irish  [light brown sugar, granulated sugar, butter, ...
39770  11462      italian  [KRAFT Zesty Italian Dressing, purple onion, b...
39771   2238        irish  [eggs, citrus fruit, raisins, sourdough starte...
39772  41882      chinese  [boneless chicken skinless thigh, minced garli...
39773   2362      mexican  [green chile, jalapeno chilies, onions, ground...

[39774 rows x 3 columns]

In [ ]:
#using url
pd.read_json('https://api.exchangerate-api.com/v4/latest/INR')

,provider,WARNING_UPGRADE_TO_V6,terms,base,date,time_last_updated,rates
INR,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-06-19,1781827202,1.0000
AED,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-06-19,1781827202,0.0389
AFN,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-06-19,1781827202,0.6740
ALL,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-06-19,1781827202,0.8740
AMD,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-06-19,1781827202,3.9000
...,...,...,...,...,...,...,...
YER,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-06-19,1781827202,2.5300
ZAR,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-06-19,1781827202,0.1740
ZMW,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-06-19,1781827202,0.1890
ZWG,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-06-19,1781827202,0.2830
ZWL,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-06-19,1781827202,0.2830

***Working with SQL***

In [ ]:
!pip install mysql.connector
#library to connect mysql to python

Collecting mysql.connector
  Downloading mysql-connector-2.2.9.tar.gz (11.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.9/11.9 MB 90.8 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: mysql.connector
  Building wheel for mysql.connector (setup.py) ... done
  Created wheel for mysql.connector: filename=mysql_connector-2.2.9-cp312-cp312-linux_x86_64.whl size=247950 sha256=69a2baaf9bd1d325ba70e53184ee3afce70063d6451dc786803e70c35ab1ef03
  Stored in directory: /root/.cache/pip/wheels/03/17/fa/d7604c72dd3dd6d3eb3d249abf36cc532c9a9b4354b8f1bc4f
Successfully built mysql.connector
Installing collected packages: mysql.connector
Successfully installed mysql.connector-2.2.9

In [ ]:
import mysql.connector

In [ ]:
conn=mysql.connector.connect(host='localhost',user='root',password='',database='world', port=3307)

InterfaceError: 2003: Can't connect to MySQL server on 'localhost:3307' (111 Connection refused)

***fetching data from api***

api= data pipelines. transfer of information

In [ ]:
import pandas as pd
import requests

In [ ]:
response = requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=587f5fd0aa118783cb93d12e2fb5d84b&language=en-US&page=1')

In [ ]:
response.json()

{'page': 1,
 'results': [{'adult': False,
   'backdrop_path': '/zMwhWailP1WY7sb6AoE6b8ugoy.jpg',
   'genre_ids': [12, 16, 10751, 14],
   'id': 1007757,
   'title': 'Swapped',
   'original_language': 'en',
   'original_title': 'Swapped',
   'overview': 'A small woodland creature and a majestic bird, two natural sworn enemies of the Valley, magically trade places and set off on an adventure of a lifetime to switch back. Their journey soon uncovers a greater threat—one that could endanger not only their species, but the entire valley they call home.',
   'popularity': 153.6512,
   'poster_path': '/tHhxWxge06goXU6ZQH1hj7vK8Hd.jpg',
   'release_date': '2026-05-01',
   'softcore': False,
   'video': False,
   'vote_average': 8.971,
   'vote_count': 1724},
  {'adult': False,
   'backdrop_path': '/zfbjgQE1uSd9wiPTX4VzsLi0rGG.jpg',
   'genre_ids': [18, 80],
   'id': 278,
   'title': 'The Shawshank Redemption',
   'original_language': 'en',
   'original_title': 'The Shawshank Redemption',
   'overview': 'Imprisoned in the 1940s for the double murder of his wife and her lover, upstanding banker Andy Dufresne begins a new life at the Shawshank prison, where he puts his accounting skills to work for an amoral warden. During his long stretch in prison, Dufresne comes to be admired by the other inmates -- including an older prisoner named Red -- for his integrity and unquenchable sense of hope.',
   'popularity': 68.7965,
   'poster_path': '/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg',
   'release_date': '1994-09-23',
   'softcore': False,
   'video': False,
   'vote_average': 8.723,
   'vote_count': 30586},
  {'adult': False,
   'backdrop_path': '/8Tfys3mDZVp4tNoH2ktm06a0Tau.jpg',
   'genre_ids': [878, 12],
   'id': 687163,
   'title': 'Project Hail Mary',
   'original_language': 'en',
   'original_title': 'Project Hail Mary',
   'overview': 'Science teacher Ryland Grace wakes up on a spaceship light years from home with no recollection of who he is or how he got there. As his memory returns, he begins to uncover his mission: solve the riddle of the mysterious substance causing the sun to die out. He must call on his scientific knowledge and unorthodox ideas to save everything on Earth from extinction.',
   'popularity': 133.9242,
   'poster_path': '/yihdXomYb5kTeSivtFndMy5iDmf.jpg',
   'release_date': '2026-03-15',
   'softcore': False,
   'video': False,
   'vote_average': 8.684,
   'vote_count': 5214},
  {'adult': False,
   'backdrop_path': '/ejdD20cdHNFAYAN2DlqPToXKyzx.jpg',
   'genre_ids': [18, 80],
   'id': 238,
   'title': 'The Godfather',
   'original_language': 'en',
   'original_title': 'The Godfather',
   'overview': 'Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family. When organized crime family patriarch, Vito Corleone barely survives an attempt on his life, his youngest son, Michael steps in to take care of the would-be killers, launching a campaign of bloody revenge.',
   'popularity': 38.1178,
   'poster_path': '/3bhkrj58Vtu7enYsRolD1fZdja1.jpg',
   'release_date': '1972-03-14',
   'softcore': False,
   'video': False,
   'vote_average': 8.7,
   'vote_count': 23052},
  {'adult': False,
   'backdrop_path': '/ufSwlnECLoUbBjPrFqEQcWBzHwc.jpg',
   'genre_ids': [10402, 18],
   'id': 936075,
   'title': 'Michael',
   'original_language': 'en',
   'original_title': 'Michael',
   'overview': 'The story of Michael Jackson, one of the most influential artists the world has ever known, and his life beyond the music. His journey from the discovery of his extraordinary talent as the lead of the Jackson Five, to the visionary artist whose creative ambition fueled a relentless pursuit to become the biggest entertainer in the world, highlighting both his life off-stage and some of the most iconic performances from his early solo career.',
   'popularity': 535.6645,
   'poster_path': '/zm0KAbOjlt9eR5y7vDiL2dEOwMl.jpg',
   'release_date': '2026-04-22',
   'softcore': False,
   'video': False,
   'vote_average': 8.657,
   'vote_count': 2694},
  {'adult': False,
   'backdrop_path': '/kGzFbGhp99zva6oZODW5atUtnqi.jpg',
   'genre_ids': [18, 80],
   'id': 240,
   'title': 'The Godfather Part II',
   'original_language': 'en',
   'original_title': 'The Godfather Part II',
   'overview': 'In the continuing saga of the Corleone crime family, a young Vito Corleone grows up in Sicily and in 1910s New York. In the 1950s, Michael Corleone attempts to expand the family business into Las Vegas, Hollywood and Cuba.',
   'popularity': 24.5254,
   'poster_path': '/hek3koDUyRQk7FIhPXsa6mT2Zc3.jpg',
   'release_date': '1974-12-20',
   'softcore': False,
   'video': False,
   'vote_average': 8.6,
   'vote_count': 13975},
  {'adult': False,
   'backdrop_path': '/zb6fM1CX41D9rF9hdgclu0peUmy.jpg',
   'genre_ids': [18, 36, 10752],
   'id': 424,
   'title': "Schindler's List",
   'original_language': 'en',
   'original_title': "Schindler's List",
   'overview': 'The true story of how businessman Oskar Schindler saved over a thousand Jewish lives from the Nazis while they worked as slaves in his factory during World War II.',
   'popularity': 21.2406,
   'poster_path': '/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg',
   'release_date': '1993-12-15',
   'softcore': False,
   'video': False,
   'vote_average': 8.569,
   'vote_count': 17525},
  {'adult': False,
   'backdrop_path': '/qqHQsStV6exghCM7zbObuYBiYxw.jpg',
   'genre_ids': [18],
   'id': 389,
   'title': '12 Angry Men',
   'original_language': 'en',
   'original_title': '12 Angry Men',
   'overview': "The defense and the prosecution have rested and the jury is filing into the jury room to decide if a young Spanish-American is guilty or innocent of murdering his father. What begins as an open and shut case soon becomes a mini-drama of each of the jurors' prejudices and preconceptions about the trial, the accused, and each other.",
   'popularity': 19.6979,
   'poster_path': '/zhG3vKWyDRaZYoaww1UVAi29T9h.jpg',
   'release_date': '1957-04-10',
   'softcore': False,
   'video': False,
   'vote_average': 8.6,
   'vote_count': 10048},
  {'adult': False,
   'backdrop_path': '/bVGHSe47W6oCQL1Q88pvRAet51A.jpg',
   'genre_ids': [18, 9648],
   'id': 1330021,
   'title': 'Remarkably Bright Creatures',
   'original_language': 'en',
   'original_title': 'Remarkably Bright Creatures',
   'overview': 'Through unlikely bonds formed during night shifts at a local aquarium, Tova, an elderly widow, learns of a life-changing discovery that may bring her joy and wonder once again.',
   'popularity': 30.2013,
   'poster_path': '/9HcEqn3D4J6b2Z0jK54id9nA0fr.jpg',
   'release_date': '2026-05-07',
   'softcore': False,
   'video': False,
   'vote_average': 8.6,
   'vote_count': 636},
  {'adult': False,
   'backdrop_path': '/dyJvKsNs2KP8qQnAXbRwDjblViy.jpg',
   'genre_ids': [16, 10751, 14],
   'id': 129,
   'title': 'Spirited Away',
   'original_language': 'ja',
   'original_title': '千と千尋の神隠し',
   'overview': 'A young girl, Chihiro, becomes trapped in a strange new world of spirits. When her parents undergo a mysterious transformation, she must call upon the courage she never knew she had to free her family.',
   'popularity': 32.7915,
   'poster_path': '/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg',
   'release_date': '2001-07-20',
   'softcore': False,
   'video': False,
   'vote_average': 8.535,
   'vote_count': 18423},
  {'adult': False,
   'backdrop_path': '/cfT29Im5VDvjE0RpyKOSdCKZal7.jpg',
   'genre_ids': [28, 80, 53],
   'id': 155,
   'title': 'The Dark Knight',
   'original_language': 'en',
   'original_title': 'The Dark Knight',
   'overview': 'Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets. The partnership proves to be effective, but they soon find themselves prey to a reign of chaos unleashed by a rising criminal mastermind known to the terrified citizens of Gotham as the Joker.',
   'popularity': 44.4786,
   'poster_path': '/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
   'release_date': '2008-07-16',
   'softcore': False,
   'video': False,
   'vote_average': 8.531,
   'vote_count': 35932},
  {'adult': False,
   'backdrop_path': '/84beTJf26mfhoasUlKSOiNSutyS.jpg',
   'genre_ids': [35, 18, 10749],
   'id': 19404,
   'title': 'Dilwale Dulhania Le Jayenge',
   'original_language': 'hi',
   'original_title': 'दिलवाले दुल्हनिया ले जायेंगे',
   'overview': 'Raj is a rich, carefree, happy-go-lucky second generation NRI. Simran is the daughter of Chaudhary Baldev Singh, who in spite of being an NRI is very strict about adherence to Indian values. Simran has left for India to be married to her childhood fiancé. Raj leaves for India with a mission at his hands, to claim his lady love under the noses of her whole family. Thus begins a saga.',
   'popularity': 14.0802,
   'poster_path': '/tFbfCkS7q6g96wVoAu8kyr93iPm.jpg',
   'release_date': '1995-10-20',
   'softcore': False,
   'video': False,
   'vote_average': 8.51,
   'vote_count': 4597},
  {'adult': False,
   'backdrop_path': '/b6HWTOxn1xevvyHU2K9ICvaRU6g.jpg',
   'genre_ids': [14, 18, 80],
   'id': 497,
   'title': 'The Green Mile',
   'original_language': 'en',
   'original_title': 'The Green Mile',
   'overview': "A supernatural tale set on death row in a Southern prison, where gentle giant John Coffey possesses the mysterious power to heal people's ailments. When the cell block's head guard, Paul Edgecomb, recognizes Coffey's miraculous gift, he tries desperately to help stave off the condemned man's execution.",
   'popularity': 24.2155,
   'poster_path': '/8VG8fDNiy50H4FedGwdSVUPoaJe.jpg',
   'release_date': '1999-12-10',
   'softcore': False,
   'video': False,
   'vote_average': 8.507,
   'vote_count': 19341},
  {'adult': False,
   'backdrop_path': '/2u7zbn8EudG6kLlBzUYqP8RyFU4.jpg',
   'genre_ids': [12, 14, 28],
   'id': 122,
   'title': 'The Lord of the Rings: The Return of the King',
   'original_language': 'en',
   'original_title': 'The Lord of the Rings: The Return of the King',
   'overview': 'As armies mass for a final battle that will decide the fate of the world--and powerful, ancient forces of Light and Dark compete to determine the outcome--one member of the Fellowship of the Ring is revealed as the noble heir to the throne of the Kings of Men. Yet, the sole hope for triumph over evil lies with a brave hobbit, Frodo, who, accompanied by his loyal friend Sam and the hideous, wretched Gollum, ventures deep into the very dark heart of Mordor on his seemingly impossible quest to destroy the Ring of Power.\u200b',
   'popularity': 38.438,
   'poster_path': '/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg',
   'release_date': '2003-12-17',
   'softcore': False,
   'video': False,
   'vote_average': 8.5,
   'vote_count': 26662},
  {'adult': False,
   'backdrop_path': '/8eihUxjQsJ7WvGySkVMC0EwbPAD.jpg',
   'genre_ids': [35, 53, 18],
   'id': 496243,
   'title': 'Parasite',
   'original_language': 'ko',
   'original_title': '기생충',
   'overview': "All unemployed, Ki-taek's family takes peculiar interest in the wealthy and glamorous Parks for their livelihood until they get entangled in an unexpected incident.",
   'popularity': 33.7178,
   'poster_path': '/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg',
   'release_date': '2019-05-30',
   'softcore': False,
   'video': False,
   'vote_average': 8.494,
   'vote_count': 20752},
  {'adult': False,
   'backdrop_path': '/xyWKrni8WrYzqn7ztvI5nIY0h62.jpg',
   'genre_ids': [35, 10749],
   'id': 1181678,
   'title': '¿Quieres ser mi hijo?',
   'original_language': 'en',
   'original_title': '¿Quieres ser mi hijo?',
   'overview': 'Lu, a conformist woman in her forties, learns that her 15-year partner has been having extramarital affairs. Starting from scratch, she gets involved in an unexpected relationship with a young womanizer.',
   'popularity': 8.0538,
   'poster_path': '/6PQJsmuvSMZQMmlJfTpjIkrizUh.jpg',
   'release_date': '2023-09-21',
   'softcore': False,
   'video': False,
   'vote_average': 8.5,
   'vote_count': 354},
  {'adult': False,
   'backdrop_path': '/suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg',
   'genre_ids': [53, 80, 35],
   'id': 680,
   'title': 'Pulp Fiction',
   'original_language': 'en',
   'original_title': 'Pulp Fiction',
   'overview': "A burger-loving hit man, his philosophical partner, a drug-addled gangster's moll and a washed-up boxer converge in this sprawling, comedic crime caper. Their adventures unfurl in three stories that ingeniously trip back and forth in time.",
   'popularity': 35.9042,
   'poster_path': '/vQWk5YBFWF4bZaofAbv0tShwBvQ.jpg',
   'release_date': '1994-09-10',
   'softcore': False,
   'video': False,
   'vote_average': 8.483,
   'vote_count': 30304},
  {'adult': False,
   'backdrop_path': '/mMtUybQ6hL24FXo0F3Z4j2KG7kZ.jpg',
   'genre_ids': [16, 10749, 18],
   'id': 372058,
   'title': 'Your Name.',
   'original_language': 'ja',
   'original_title': '君の名は。',
   'overview': 'High schoolers Mitsuha and Taki are complete strangers living separate lives. But one night, they suddenly switch places. Mitsuha wakes up in Taki’s body, and he in hers. This bizarre occurrence continues to happen randomly, and the two must adjust their lives around each other.',
   'popularity': 25.2944,
   'poster_path': '/q719jXXEzOoYaps6babgKnONONX.jpg',
   'release_date': '2016-08-26',
   'softcore': False,
   'video': False,
   'vote_average': 8.481,
   'vote_count': 12627},
  {'adult': False,
   'backdrop_path': '/2ssWTSVklAEc98frZUQhgtGHx7s.jpg',
   'genre_ids': [12, 18, 878],
   'id': 157336,
   'title': 'Interstellar',
   'original_language': 'en',
   'original_title': 'Interstellar',
   'overview': 'The adventures of a group of explorers who make use of a newly discovered wormhole to surpass the limitations on human space travel and conquer the vast distances involved in an interstellar voyage.',
   'popularity': 67.8031,
   'poster_path': '/yQvGrMoipbRoddT0ZR8tPoR7NfX.jpg',
   'release_date': '2014-11-05',
   'softcore': False,
   'video': False,
   'vote_average': 8.478,
   'vote_count': 40054},
  {'adult': False,
   'backdrop_path': '/Adrip2Jqzw56KeuV2nAxucKMNXA.jpg',
   'genre_ids': [37],
   'id': 429,
   'title': 'The Good, the Bad and the Ugly',
   'original_language': 'it',
   'original_title': 'Il buono, il brutto, il cattivo',
   'overview': 'While the Civil War rages on between the Union and the Confederacy, three men – a quiet loner, a ruthless hitman, and a Mexican bandit – comb the American Southwest in search of a strongbox containing $200,000 in stolen gold.',
   'popularity': 17.4217,
   'poster_path': '/bX2xnavhMYjWDoZp1VM6VnU1xwe.jpg',
   'release_date': '1966-12-23',
   'softcore': False,
   'video': False,
   'vote_average': 8.468,
   'vote_count': 9692}],
 'total_pages': 547,
 'total_results': 10939}

In [ ]:
response.json()['results']

[{'adult': False,
  'backdrop_path': '/zMwhWailP1WY7sb6AoE6b8ugoy.jpg',
  'genre_ids': [12, 16, 10751, 14],
  'id': 1007757,
  'title': 'Swapped',
  'original_language': 'en',
  'original_title': 'Swapped',
  'overview': 'A small woodland creature and a majestic bird, two natural sworn enemies of the Valley, magically trade places and set off on an adventure of a lifetime to switch back. Their journey soon uncovers a greater threat—one that could endanger not only their species, but the entire valley they call home.',
  'popularity': 153.6512,
  'poster_path': '/tHhxWxge06goXU6ZQH1hj7vK8Hd.jpg',
  'release_date': '2026-05-01',
  'softcore': False,
  'video': False,
  'vote_average': 8.971,
  'vote_count': 1724},
 {'adult': False,
  'backdrop_path': '/zfbjgQE1uSd9wiPTX4VzsLi0rGG.jpg',
  'genre_ids': [18, 80],
  'id': 278,
  'title': 'The Shawshank Redemption',
  'original_language': 'en',
  'original_title': 'The Shawshank Redemption',
  'overview': 'Imprisoned in the 1940s for the double murder of his wife and her lover, upstanding banker Andy Dufresne begins a new life at the Shawshank prison, where he puts his accounting skills to work for an amoral warden. During his long stretch in prison, Dufresne comes to be admired by the other inmates -- including an older prisoner named Red -- for his integrity and unquenchable sense of hope.',
  'popularity': 68.7965,
  'poster_path': '/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg',
  'release_date': '1994-09-23',
  'softcore': False,
  'video': False,
  'vote_average': 8.723,
  'vote_count': 30586},
 {'adult': False,
  'backdrop_path': '/8Tfys3mDZVp4tNoH2ktm06a0Tau.jpg',
  'genre_ids': [878, 12],
  'id': 687163,
  'title': 'Project Hail Mary',
  'original_language': 'en',
  'original_title': 'Project Hail Mary',
  'overview': 'Science teacher Ryland Grace wakes up on a spaceship light years from home with no recollection of who he is or how he got there. As his memory returns, he begins to uncover his mission: solve the riddle of the mysterious substance causing the sun to die out. He must call on his scientific knowledge and unorthodox ideas to save everything on Earth from extinction.',
  'popularity': 133.9242,
  'poster_path': '/yihdXomYb5kTeSivtFndMy5iDmf.jpg',
  'release_date': '2026-03-15',
  'softcore': False,
  'video': False,
  'vote_average': 8.684,
  'vote_count': 5214},
 {'adult': False,
  'backdrop_path': '/ejdD20cdHNFAYAN2DlqPToXKyzx.jpg',
  'genre_ids': [18, 80],
  'id': 238,
  'title': 'The Godfather',
  'original_language': 'en',
  'original_title': 'The Godfather',
  'overview': 'Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family. When organized crime family patriarch, Vito Corleone barely survives an attempt on his life, his youngest son, Michael steps in to take care of the would-be killers, launching a campaign of bloody revenge.',
  'popularity': 38.1178,
  'poster_path': '/3bhkrj58Vtu7enYsRolD1fZdja1.jpg',
  'release_date': '1972-03-14',
  'softcore': False,
  'video': False,
  'vote_average': 8.7,
  'vote_count': 23052},
 {'adult': False,
  'backdrop_path': '/ufSwlnECLoUbBjPrFqEQcWBzHwc.jpg',
  'genre_ids': [10402, 18],
  'id': 936075,
  'title': 'Michael',
  'original_language': 'en',
  'original_title': 'Michael',
  'overview': 'The story of Michael Jackson, one of the most influential artists the world has ever known, and his life beyond the music. His journey from the discovery of his extraordinary talent as the lead of the Jackson Five, to the visionary artist whose creative ambition fueled a relentless pursuit to become the biggest entertainer in the world, highlighting both his life off-stage and some of the most iconic performances from his early solo career.',
  'popularity': 535.6645,
  'poster_path': '/zm0KAbOjlt9eR5y7vDiL2dEOwMl.jpg',
  'release_date': '2026-04-22',
  'softcore': False,
  'video': False,
  'vote_average': 8.657,
  'vote_count': 2694},
 {'adult': False,
  'backdrop_path': '/kGzFbGhp99zva6oZODW5atUtnqi.jpg',
  'genre_ids': [18, 80],
  'id': 240,
  'title': 'The Godfather Part II',
  'original_language': 'en',
  'original_title': 'The Godfather Part II',
  'overview': 'In the continuing saga of the Corleone crime family, a young Vito Corleone grows up in Sicily and in 1910s New York. In the 1950s, Michael Corleone attempts to expand the family business into Las Vegas, Hollywood and Cuba.',
  'popularity': 24.5254,
  'poster_path': '/hek3koDUyRQk7FIhPXsa6mT2Zc3.jpg',
  'release_date': '1974-12-20',
  'softcore': False,
  'video': False,
  'vote_average': 8.6,
  'vote_count': 13975},
 {'adult': False,
  'backdrop_path': '/zb6fM1CX41D9rF9hdgclu0peUmy.jpg',
  'genre_ids': [18, 36, 10752],
  'id': 424,
  'title': "Schindler's List",
  'original_language': 'en',
  'original_title': "Schindler's List",
  'overview': 'The true story of how businessman Oskar Schindler saved over a thousand Jewish lives from the Nazis while they worked as slaves in his factory during World War II.',
  'popularity': 21.2406,
  'poster_path': '/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg',
  'release_date': '1993-12-15',
  'softcore': False,
  'video': False,
  'vote_average': 8.569,
  'vote_count': 17525},
 {'adult': False,
  'backdrop_path': '/qqHQsStV6exghCM7zbObuYBiYxw.jpg',
  'genre_ids': [18],
  'id': 389,
  'title': '12 Angry Men',
  'original_language': 'en',
  'original_title': '12 Angry Men',
  'overview': "The defense and the prosecution have rested and the jury is filing into the jury room to decide if a young Spanish-American is guilty or innocent of murdering his father. What begins as an open and shut case soon becomes a mini-drama of each of the jurors' prejudices and preconceptions about the trial, the accused, and each other.",
  'popularity': 19.6979,
  'poster_path': '/zhG3vKWyDRaZYoaww1UVAi29T9h.jpg',
  'release_date': '1957-04-10',
  'softcore': False,
  'video': False,
  'vote_average': 8.6,
  'vote_count': 10048},
 {'adult': False,
  'backdrop_path': '/bVGHSe47W6oCQL1Q88pvRAet51A.jpg',
  'genre_ids': [18, 9648],
  'id': 1330021,
  'title': 'Remarkably Bright Creatures',
  'original_language': 'en',
  'original_title': 'Remarkably Bright Creatures',
  'overview': 'Through unlikely bonds formed during night shifts at a local aquarium, Tova, an elderly widow, learns of a life-changing discovery that may bring her joy and wonder once again.',
  'popularity': 30.2013,
  'poster_path': '/9HcEqn3D4J6b2Z0jK54id9nA0fr.jpg',
  'release_date': '2026-05-07',
  'softcore': False,
  'video': False,
  'vote_average': 8.6,
  'vote_count': 636},
 {'adult': False,
  'backdrop_path': '/dyJvKsNs2KP8qQnAXbRwDjblViy.jpg',
  'genre_ids': [16, 10751, 14],
  'id': 129,
  'title': 'Spirited Away',
  'original_language': 'ja',
  'original_title': '千と千尋の神隠し',
  'overview': 'A young girl, Chihiro, becomes trapped in a strange new world of spirits. When her parents undergo a mysterious transformation, she must call upon the courage she never knew she had to free her family.',
  'popularity': 32.7915,
  'poster_path': '/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg',
  'release_date': '2001-07-20',
  'softcore': False,
  'video': False,
  'vote_average': 8.535,
  'vote_count': 18423},
 {'adult': False,
  'backdrop_path': '/cfT29Im5VDvjE0RpyKOSdCKZal7.jpg',
  'genre_ids': [28, 80, 53],
  'id': 155,
  'title': 'The Dark Knight',
  'original_language': 'en',
  'original_title': 'The Dark Knight',
  'overview': 'Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets. The partnership proves to be effective, but they soon find themselves prey to a reign of chaos unleashed by a rising criminal mastermind known to the terrified citizens of Gotham as the Joker.',
  'popularity': 44.4786,
  'poster_path': '/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
  'release_date': '2008-07-16',
  'softcore': False,
  'video': False,
  'vote_average': 8.531,
  'vote_count': 35932},
 {'adult': False,
  'backdrop_path': '/84beTJf26mfhoasUlKSOiNSutyS.jpg',
  'genre_ids': [35, 18, 10749],
  'id': 19404,
  'title': 'Dilwale Dulhania Le Jayenge',
  'original_language': 'hi',
  'original_title': 'दिलवाले दुल्हनिया ले जायेंगे',
  'overview': 'Raj is a rich, carefree, happy-go-lucky second generation NRI. Simran is the daughter of Chaudhary Baldev Singh, who in spite of being an NRI is very strict about adherence to Indian values. Simran has left for India to be married to her childhood fiancé. Raj leaves for India with a mission at his hands, to claim his lady love under the noses of her whole family. Thus begins a saga.',
  'popularity': 14.0802,
  'poster_path': '/tFbfCkS7q6g96wVoAu8kyr93iPm.jpg',
  'release_date': '1995-10-20',
  'softcore': False,
  'video': False,
  'vote_average': 8.51,
  'vote_count': 4597},
 {'adult': False,
  'backdrop_path': '/b6HWTOxn1xevvyHU2K9ICvaRU6g.jpg',
  'genre_ids': [14, 18, 80],
  'id': 497,
  'title': 'The Green Mile',
  'original_language': 'en',
  'original_title': 'The Green Mile',
  'overview': "A supernatural tale set on death row in a Southern prison, where gentle giant John Coffey possesses the mysterious power to heal people's ailments. When the cell block's head guard, Paul Edgecomb, recognizes Coffey's miraculous gift, he tries desperately to help stave off the condemned man's execution.",
  'popularity': 24.2155,
  'poster_path': '/8VG8fDNiy50H4FedGwdSVUPoaJe.jpg',
  'release_date': '1999-12-10',
  'softcore': False,
  'video': False,
  'vote_average': 8.507,
  'vote_count': 19341},
 {'adult': False,
  'backdrop_path': '/2u7zbn8EudG6kLlBzUYqP8RyFU4.jpg',
  'genre_ids': [12, 14, 28],
  'id': 122,
  'title': 'The Lord of the Rings: The Return of the King',
  'original_language': 'en',
  'original_title': 'The Lord of the Rings: The Return of the King',
  'overview': 'As armies mass for a final battle that will decide the fate of the world--and powerful, ancient forces of Light and Dark compete to determine the outcome--one member of the Fellowship of the Ring is revealed as the noble heir to the throne of the Kings of Men. Yet, the sole hope for triumph over evil lies with a brave hobbit, Frodo, who, accompanied by his loyal friend Sam and the hideous, wretched Gollum, ventures deep into the very dark heart of Mordor on his seemingly impossible quest to destroy the Ring of Power.\u200b',
  'popularity': 38.438,
  'poster_path': '/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg',
  'release_date': '2003-12-17',
  'softcore': False,
  'video': False,
  'vote_average': 8.5,
  'vote_count': 26662},
 {'adult': False,
  'backdrop_path': '/8eihUxjQsJ7WvGySkVMC0EwbPAD.jpg',
  'genre_ids': [35, 53, 18],
  'id': 496243,
  'title': 'Parasite',
  'original_language': 'ko',
  'original_title': '기생충',
  'overview': "All unemployed, Ki-taek's family takes peculiar interest in the wealthy and glamorous Parks for their livelihood until they get entangled in an unexpected incident.",
  'popularity': 33.7178,
  'poster_path': '/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg',
  'release_date': '2019-05-30',
  'softcore': False,
  'video': False,
  'vote_average': 8.494,
  'vote_count': 20752},
 {'adult': False,
  'backdrop_path': '/xyWKrni8WrYzqn7ztvI5nIY0h62.jpg',
  'genre_ids': [35, 10749],
  'id': 1181678,
  'title': '¿Quieres ser mi hijo?',
  'original_language': 'en',
  'original_title': '¿Quieres ser mi hijo?',
  'overview': 'Lu, a conformist woman in her forties, learns that her 15-year partner has been having extramarital affairs. Starting from scratch, she gets involved in an unexpected relationship with a young womanizer.',
  'popularity': 8.0538,
  'poster_path': '/6PQJsmuvSMZQMmlJfTpjIkrizUh.jpg',
  'release_date': '2023-09-21',
  'softcore': False,
  'video': False,
  'vote_average': 8.5,
  'vote_count': 354},
 {'adult': False,
  'backdrop_path': '/suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg',
  'genre_ids': [53, 80, 35],
  'id': 680,
  'title': 'Pulp Fiction',
  'original_language': 'en',
  'original_title': 'Pulp Fiction',
  'overview': "A burger-loving hit man, his philosophical partner, a drug-addled gangster's moll and a washed-up boxer converge in this sprawling, comedic crime caper. Their adventures unfurl in three stories that ingeniously trip back and forth in time.",
  'popularity': 35.9042,
  'poster_path': '/vQWk5YBFWF4bZaofAbv0tShwBvQ.jpg',
  'release_date': '1994-09-10',
  'softcore': False,
  'video': False,
  'vote_average': 8.483,
  'vote_count': 30304},
 {'adult': False,
  'backdrop_path': '/mMtUybQ6hL24FXo0F3Z4j2KG7kZ.jpg',
  'genre_ids': [16, 10749, 18],
  'id': 372058,
  'title': 'Your Name.',
  'original_language': 'ja',
  'original_title': '君の名は。',
  'overview': 'High schoolers Mitsuha and Taki are complete strangers living separate lives. But one night, they suddenly switch places. Mitsuha wakes up in Taki’s body, and he in hers. This bizarre occurrence continues to happen randomly, and the two must adjust their lives around each other.',
  'popularity': 25.2944,
  'poster_path': '/q719jXXEzOoYaps6babgKnONONX.jpg',
  'release_date': '2016-08-26',
  'softcore': False,
  'video': False,
  'vote_average': 8.481,
  'vote_count': 12627},
 {'adult': False,
  'backdrop_path': '/2ssWTSVklAEc98frZUQhgtGHx7s.jpg',
  'genre_ids': [12, 18, 878],
  'id': 157336,
  'title': 'Interstellar',
  'original_language': 'en',
  'original_title': 'Interstellar',
  'overview': 'The adventures of a group of explorers who make use of a newly discovered wormhole to surpass the limitations on human space travel and conquer the vast distances involved in an interstellar voyage.',
  'popularity': 67.8031,
  'poster_path': '/yQvGrMoipbRoddT0ZR8tPoR7NfX.jpg',
  'release_date': '2014-11-05',
  'softcore': False,
  'video': False,
  'vote_average': 8.478,
  'vote_count': 40054},
 {'adult': False,
  'backdrop_path': '/Adrip2Jqzw56KeuV2nAxucKMNXA.jpg',
  'genre_ids': [37],
  'id': 429,
  'title': 'The Good, the Bad and the Ugly',
  'original_language': 'it',
  'original_title': 'Il buono, il brutto, il cattivo',
  'overview': 'While the Civil War rages on between the Union and the Confederacy, three men – a quiet loner, a ruthless hitman, and a Mexican bandit – comb the American Southwest in search of a strongbox containing $200,000 in stolen gold.',
  'popularity': 17.4217,
  'poster_path': '/bX2xnavhMYjWDoZp1VM6VnU1xwe.jpg',
  'release_date': '1966-12-23',
  'softcore': False,
  'video': False,
  'vote_average': 8.468,
  'vote_count': 9692}]

In [ ]:
pd.DataFrame(response.json()['results'])

,adult,backdrop_path,genre_ids,id,title,original_language,original_title,overview,popularity,poster_path,release_date,softcore,video,vote_average,vote_count
0,False,/zMwhWailP1WY7sb6AoE6b8ugoy.jpg,"[12, 16, 10751, 14]",1007757,Swapped,en,Swapped,"A small woodland creature and a majestic bird,...",153.6512,/tHhxWxge06goXU6ZQH1hj7vK8Hd.jpg,2026-05-01,False,False,8.971,1724
1,False,/zfbjgQE1uSd9wiPTX4VzsLi0rGG.jpg,"[18, 80]",278,The Shawshank Redemption,en,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,68.7965,/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg,1994-09-23,False,False,8.723,30586
2,False,/8Tfys3mDZVp4tNoH2ktm06a0Tau.jpg,"[878, 12]",687163,Project Hail Mary,en,Project Hail Mary,Science teacher Ryland Grace wakes up on a spa...,133.9242,/yihdXomYb5kTeSivtFndMy5iDmf.jpg,2026-03-15,False,False,8.684,5214
3,False,/ejdD20cdHNFAYAN2DlqPToXKyzx.jpg,"[18, 80]",238,The Godfather,en,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",38.1178,/3bhkrj58Vtu7enYsRolD1fZdja1.jpg,1972-03-14,False,False,8.700,23052
4,False,/ufSwlnECLoUbBjPrFqEQcWBzHwc.jpg,"[10402, 18]",936075,Michael,en,Michael,"The story of Michael Jackson, one of the most ...",535.6645,/zm0KAbOjlt9eR5y7vDiL2dEOwMl.jpg,2026-04-22,False,False,8.657,2694
5,False,/kGzFbGhp99zva6oZODW5atUtnqi.jpg,"[18, 80]",240,The Godfather Part II,en,The Godfather Part II,In the continuing saga of the Corleone crime f...,24.5254,/hek3koDUyRQk7FIhPXsa6mT2Zc3.jpg,1974-12-20,False,False,8.600,13975
6,False,/zb6fM1CX41D9rF9hdgclu0peUmy.jpg,"[18, 36, 10752]",424,Schindler's List,en,Schindler's List,The true story of how businessman Oskar Schind...,21.2406,/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg,1993-12-15,False,False,8.569,17525
7,False,/qqHQsStV6exghCM7zbObuYBiYxw.jpg,[18],389,12 Angry Men,en,12 Angry Men,The defense and the prosecution have rested an...,19.6979,/zhG3vKWyDRaZYoaww1UVAi29T9h.jpg,1957-04-10,False,False,8.600,10048
8,False,/bVGHSe47W6oCQL1Q88pvRAet51A.jpg,"[18, 9648]",1330021,Remarkably Bright Creatures,en,Remarkably Bright Creatures,Through unlikely bonds formed during night shi...,30.2013,/9HcEqn3D4J6b2Z0jK54id9nA0fr.jpg,2026-05-07,False,False,8.600,636
9,False,/dyJvKsNs2KP8qQnAXbRwDjblViy.jpg,"[16, 10751, 14]",129,Spirited Away,ja,千と千尋の神隠し,"A young girl, Chihiro, becomes trapped in a st...",32.7915,/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg,2001-07-20,False,False,8.535,18423
10,False,/cfT29Im5VDvjE0RpyKOSdCKZal7.jpg,"[28, 80, 53]",155,The Dark Knight,en,The Dark Knight,Batman raises the stakes in his war on crime. ...,44.4786,/qJ2tW6WMUDux911r6m7haRef0WH.jpg,2008-07-16,False,False,8.531,35932
11,False,/84beTJf26mfhoasUlKSOiNSutyS.jpg,"[35, 18, 10749]",19404,Dilwale Dulhania Le Jayenge,hi,दिलवाले दुल्हनिया ले जायेंगे,"Raj is a rich, carefree, happy-go-lucky second...",14.0802,/tFbfCkS7q6g96wVoAu8kyr93iPm.jpg,1995-10-20,False,False,8.510,4597
12,False,/b6HWTOxn1xevvyHU2K9ICvaRU6g.jpg,"[14, 18, 80]",497,The Green Mile,en,The Green Mile,A supernatural tale set on death row in a Sout...,24.2155,/8VG8fDNiy50H4FedGwdSVUPoaJe.jpg,1999-12-10,False,False,8.507,19341
13,False,/2u7zbn8EudG6kLlBzUYqP8RyFU4.jpg,"[12, 14, 28]",122,The Lord of the Rings: The Return of the King,en,The Lord of the Rings: The Return of the King,As armies mass for a final battle that will de...,38.4380,/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg,2003-12-17,False,False,8.500,26662
14,False,/8eihUxjQsJ7WvGySkVMC0EwbPAD.jpg,"[35, 53, 18]",496243,Parasite,ko,기생충,"All unemployed, Ki-taek's family takes peculia...",33.7178,/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg,2019-05-30,False,False,8.494,20752
15,False,/xyWKrni8WrYzqn7ztvI5nIY0h62.jpg,"[35, 10749]",1181678,¿Quieres ser mi hijo?,en,¿Quieres ser mi hijo?,"Lu, a conformist woman in her forties, learns ...",8.0538,/6PQJsmuvSMZQMmlJfTpjIkrizUh.jpg,2023-09-21,False,False,8.500,354
16,False,/suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg,"[53, 80, 35]",680,Pulp Fiction,en,Pulp Fiction,"A burger-loving hit man, his philosophical par...",35.9042,/vQWk5YBFWF4bZaofAbv0tShwBvQ.jpg,1994-09-10,False,False,8.483,30304
17,False,/mMtUybQ6hL24FXo0F3Z4j2KG7kZ.jpg,"[16, 10749, 18]",372058,Your Name.,ja,君の名は。,High schoolers Mitsuha and Taki are complete s...,25.2944,/q719jXXEzOoYaps6babgKnONONX.jpg,2016-08-26,False,False,8.481,12627
18,False,/2ssWTSVklAEc98frZUQhgtGHx7s.jpg,"[12, 18, 878]",157336,Interstellar,en,Interstellar,The adventures of a group of explorers who mak...,67.8031,/yQvGrMoipbRoddT0ZR8tPoR7NfX.jpg,2014-11-05,False,False,8.478,40054
19,False,/Adrip2Jqzw56KeuV2nAxucKMNXA.jpg,[37],429,"The Good, the Bad and the Ugly",it,"Il buono, il brutto, il cattivo",While the Civil War rages on between the Union...,17.4217,/bX2xnavhMYjWDoZp1VM6VnU1xwe.jpg,1966-12-23,False,False,8.468,9692

In [ ]:
pd.DataFrame(response.json()['results'],columns=['id','title','overview','release_date','popularity'])

,id,title,overview,release_date,popularity
0,1007757,Swapped,"A small woodland creature and a majestic bird,...",2026-05-01,153.6512
1,278,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,1994-09-23,68.7965
2,687163,Project Hail Mary,Science teacher Ryland Grace wakes up on a spa...,2026-03-15,133.9242
3,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",1972-03-14,38.1178
4,936075,Michael,"The story of Michael Jackson, one of the most ...",2026-04-22,535.6645
5,240,The Godfather Part II,In the continuing saga of the Corleone crime f...,1974-12-20,24.5254
6,424,Schindler's List,The true story of how businessman Oskar Schind...,1993-12-15,21.2406
7,389,12 Angry Men,The defense and the prosecution have rested an...,1957-04-10,19.6979
8,1330021,Remarkably Bright Creatures,Through unlikely bonds formed during night shi...,2026-05-07,30.2013
9,129,Spirited Away,"A young girl, Chihiro, becomes trapped in a st...",2001-07-20,32.7915
10,155,The Dark Knight,Batman raises the stakes in his war on crime. ...,2008-07-16,44.4786
11,19404,Dilwale Dulhania Le Jayenge,"Raj is a rich, carefree, happy-go-lucky second...",1995-10-20,14.0802
12,497,The Green Mile,A supernatural tale set on death row in a Sout...,1999-12-10,24.2155
13,122,The Lord of the Rings: The Return of the King,As armies mass for a final battle that will de...,2003-12-17,38.4380
14,496243,Parasite,"All unemployed, Ki-taek's family takes peculia...",2019-05-30,33.7178
15,1181678,¿Quieres ser mi hijo?,"Lu, a conformist woman in her forties, learns ...",2023-09-21,8.0538
16,680,Pulp Fiction,"A burger-loving hit man, his philosophical par...",1994-09-10,35.9042
17,372058,Your Name.,High schoolers Mitsuha and Taki are complete s...,2016-08-26,25.2944
18,157336,Interstellar,The adventures of a group of explorers who mak...,2014-11-05,67.8031
19,429,"The Good, the Bad and the Ugly",While the Civil War rages on between the Union...,1966-12-23,17.4217

In [ ]:
df=pd.DataFrame()

In [ ]:
for i in range(1,501):
  response = requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=587f5fd0aa118783cb93d12e2fb5d84b&language=en-US&page={}'.format(i))

  # Check if the request was successful
  if response.status_code == 200:
    json_data = response.json()
    if 'results' in json_data:
      temp_df=pd.DataFrame(json_data['results'],columns=['id','title','overview','release_date'])
      df=pd.concat([df, temp_df], ignore_index=True)
    else:
      print(f"Warning: 'results' key not found in response for page {i}. Full response: {json_data}")
  else:
    print(f"Error: API request failed for page {i} with status code {response.status_code}. Response: {response.text}")

In [ ]:
df.shape

(33060, 4)

In [ ]:
df.to_csv('movies.csv')

In [ ]:
print(df)

            id                     title  \
0      1007757                   Swapped
1          278  The Shawshank Redemption
2       687163         Project Hail Mary
3          238             The Godfather
4       936075                   Michael
...        ...                       ...
33055   397415   Vengeance: A Love Story
33056  1096342         Beautiful Wedding
33057   823461             Good on Paper
33058    10802                 Showgirls
33059   842934                Poker Face

                                                overview release_date
0      A small woodland creature and a majestic bird,...   2026-05-01
1      Imprisoned in the 1940s for the double murder ...   1994-09-23
2      Science teacher Ryland Grace wakes up on a spa...   2026-03-15
3      Spanning the years 1945 to 1955, a chronicle o...   1972-03-14
4      The story of Michael Jackson, one of the most ...   2026-04-22
...                                                  ...          ...
33055  When a new friend is brutally assaulted, Detec...   2017-03-16
33056  Abby and Travis wake after a crazy night in Ve...   2024-01-24
33057  After years of putting her career ahead of lov...   2021-06-23
33058  Fresh to Las Vegas with no connections, Nomi M...   1995-09-22
33059  A yearly high-stakes poker game between childh...   2022-11-16

[33060 rows x 4 columns]

***USING WEB SCRAPING***

website with no apis.

In [ ]:
import pandas as pd
import requests
from bs4 import BeautifulSoup

In [ ]:
requests.get('https://www.ambitionbox.com/list-of-companies?campaign=desktop_nav&page=1').text

'<HTML><HEAD>\n<TITLE>Access Denied</TITLE>\n</HEAD><BODY>\n<H1>Access Denied</H1>\n \nYou don\'t have permission to access "http&#58;&#47;&#47;www&#46;ambitionbox&#46;com&#47;list&#45;of&#45;companies&#63;" on this server.<P>\nReference&#32;&#35;18&#46;be9da17&#46;1781971980&#46;398f5c0a\n<P>https&#58;&#47;&#47;errors&#46;edgesuite&#46;net&#47;18&#46;be9da17&#46;1781971980&#46;398f5c0a</P>\n</BODY>\n</HTML>\n'

access denied

In [ ]:
headers={'User-Agent': 'Mozilla/5.0(Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.162 Safari/537.36'}
webpage=requests.get('https://www.ambitionbox.com/list-of-companies?campaign=desktop_nav&page=1',headers=headers)

KeyboardInterrupt: