<a href="https://colab.research.google.com/github/dibyanshu999/Exploratory-Data-analysis-in-python/blob/main/ENCODING_CATEGORICAL_DATA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df = pd.read_csv('customer.csv')

In [ ]:
df.sample(5)

    age  gender   review education purchased
29   83  Female  Average        UG       Yes
17   22  Female     Poor        UG       Yes
13   57  Female  Average    School        No
21   32    Male  Average        PG        No
36   34  Female     Good        UG       Yes

In [ ]:
df = df.iloc[:,2:]

In [ ]:
df.head()

    review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,0:2],df.iloc[:,-1],test_size=0.2)

In [ ]:
X_train

     review education
0   Average    School
32  Average        UG
9      Good        UG
41     Good        PG
48     Good        UG
25     Good    School
5   Average    School
33     Good        PG
38     Good    School
3      Good        PG
36     Good        UG
17     Poor        UG
45     Poor        PG
20  Average    School
44  Average        UG
28     Poor    School
29  Average        UG
49     Good        UG
42     Good        PG
21  Average        PG
16     Poor        UG
37  Average        PG
8   Average        UG
30  Average        UG
6      Good    School
27     Poor        PG
15     Poor        UG
11     Good        UG
23     Good    School
47     Good        PG
2      Good        PG
18     Good    School
46     Poor        PG
1      Poor        UG
43     Poor        PG
22     Poor        PG
24  Average        PG
14     Poor        PG
4   Average        UG
13  Average    School

In [ ]:
from sklearn.preprocessing import OrdinalEncoder

In [ ]:
oe= OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])

In [ ]:
oe.fit(X_train)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [ ]:
X_train=oe.transform(X_train)
X_test=oe.transform(X_test)

In [ ]:
X_train

array([[1., 0.],
       [1., 1.],
       [2., 1.],
       [2., 2.],
       [2., 1.],
       [2., 0.],
       [1., 0.],
       [2., 2.],
       [2., 0.],
       [2., 2.],
       [2., 1.],
       [0., 1.],
       [0., 2.],
       [1., 0.],
       [1., 1.],
       [0., 0.],
       [1., 1.],
       [2., 1.],
       [2., 2.],
       [1., 2.],
       [0., 1.],
       [1., 2.],
       [1., 1.],
       [1., 1.],
       [2., 0.],
       [0., 2.],
       [0., 1.],
       [2., 1.],
       [2., 0.],
       [2., 2.],
       [2., 2.],
       [2., 0.],
       [0., 2.],
       [0., 1.],
       [0., 2.],
       [0., 2.],
       [1., 2.],
       [0., 2.],
       [1., 1.],
       [1., 0.]])

In [ ]:
oe.categories_

[]

In [ ]:
X_train

array([[1., 0.],
       [1., 1.],
       [2., 1.],
       [2., 2.],
       [2., 1.],
       [2., 0.],
       [1., 0.],
       [2., 2.],
       [2., 0.],
       [2., 2.],
       [2., 1.],
       [0., 1.],
       [0., 2.],
       [1., 0.],
       [1., 1.],
       [0., 0.],
       [1., 1.],
       [2., 1.],
       [2., 2.],
       [1., 2.],
       [0., 1.],
       [1., 2.],
       [1., 1.],
       [1., 1.],
       [2., 0.],
       [0., 2.],
       [0., 1.],
       [2., 1.],
       [2., 0.],
       [2., 2.],
       [2., 2.],
       [2., 0.],
       [0., 2.],
       [0., 1.],
       [0., 2.],
       [0., 2.],
       [1., 2.],
       [0., 2.],
       [1., 1.],
       [1., 0.]])

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
le = LabelEncoder()

In [ ]:
le.fit(y_train)

LabelEncoder()

In [ ]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [ ]:
y_train = le.transform(y_train)
y_test = le.transform(y_test)

In [ ]:
y_train

array([0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0])